/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fib_FibActivity */

#ifndef _Included_com_fib_FibActivity
#define _Included_com_fib_FibActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fib_FibActivity
 * Method:    fibN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_fib_FibActivity_fibN
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_fib_FibActivity
 * Method:    asyncFibN
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fib_FibActivity_asyncFibN
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
